# Homework 1 - Numpy

For all the questions, print the results with a variable of your choice (e.g., Z)

#### 1. Import the numpy package under the name `np` 

In [ ]:
import numpy as np

#### 2. Create a vector with values ranging from 10 to 49 

In [ ]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 3. Reverse a vector (first element becomes last) 

In [ ]:
a = np.arange(10,50)
reverse = a[::-1]
print(reverse)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 4. Create a 3x3 matrix with values ranging from 0 to 8 

In [ ]:
b = np.arange(0,9).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 5. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [ ]:
x =np.array([1,2,0,0,4,0])
non_zeros = np.nonzero(x)
print(non_zeros)

(array([0, 1, 4]),)


#### 6. Create a 3x3 identity matrix 

In [ ]:
size3_Identity = np.eye(3)
print(size3_Identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 7. Create a 3x3x3 array with random values 

In [ ]:
random = np.random.random((3,3,3))
print(random)

[[[0.29329011 0.02596752 0.06358726]
  [0.15573715 0.39856258 0.72744304]
  [0.50044645 0.61059932 0.12763983]]

 [[0.72612076 0.71473032 0.98532856]
  [0.14894504 0.3409795  0.70108798]
  [0.17176653 0.13621056 0.58391638]]

 [[0.92144266 0.18236531 0.80677131]
  [0.75566607 0.17516381 0.58460206]
  [0.77392548 0.56330015 0.47660893]]]


#### 8. Create a 10x10 array with random values and find the minimum and maximum values 

In [ ]:
arr = np.random.random((10,10))

max = np.max(arr)
min = np.min(arr)

print('Given array: \n', arr)
print()
print('maximum value:', max)
print()
print('minimum value:', min)

Given array: 
 [[0.97708719 0.9574233  0.74168018 0.0532567  0.67806745 0.51564306
  0.91700013 0.79853787 0.69486843 0.95912788]
 [0.24443005 0.35462125 0.62256808 0.11549149 0.67898634 0.34445806
  0.58890014 0.47359822 0.93131304 0.72075776]
 [0.65914006 0.52838564 0.72818033 0.86987229 0.56734988 0.0021527
  0.32887137 0.10616782 0.02371624 0.96246414]
 [0.361716   0.81205716 0.87349198 0.72956046 0.46606184 0.30484401
  0.04349326 0.62149848 0.58831925 0.43585839]
 [0.67961042 0.61997299 0.45095572 0.2522355  0.53415503 0.17754517
  0.47449641 0.04002925 0.6101682  0.17767783]
 [0.98034657 0.14405095 0.53515188 0.90185419 0.93833443 0.76768526
  0.3906719  0.7256735  0.78320436 0.6107563 ]
 [0.87506776 0.90583413 0.02500854 0.59542767 0.60092082 0.90669142
  0.31797339 0.35257405 0.70598569 0.47022064]
 [0.94197179 0.89907903 0.67440189 0.46356106 0.89685463 0.15205509
  0.13783409 0.58767075 0.86455341 0.79614013]
 [0.84989479 0.84776389 0.68944895 0.77092541 0.95420269 0.6626832

#### 9. Create a checkerboard 8x8 matrix using np.array([0,1],[1,0]) and the tile function  

In [ ]:
a = np.array([[0,1],[1,0]])
checkerboard = np.tile(a, (4,4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 10. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [ ]:
a = np.random.random((5,3))
b = np.random.random((3,2))

product = a @ b 

# you can use either 1 or 2
# 1.
print("Method 1: \n", product)
print()
# 2.
print("Method 2: \n", a.dot(b))

Method 1: 
 [[0.7501275  1.48279483]
 [0.31683305 1.00058664]
 [0.59862406 0.97006132]
 [0.56012871 1.13536492]
 [0.65805222 1.36811019]]

Method 2: 
 [[0.7501275  1.48279483]
 [0.31683305 1.00058664]
 [0.59862406 0.97006132]
 [0.56012871 1.13536492]
 [0.65805222 1.36811019]]


#### 11. Create a 5x5 matrix with row values ranging from 0 to 4 using tile function as follows:


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [ ]:
a = np.arange(0,5)
tile = np.tile(a, (4,1))

print(tile)
print()

# just in case, to get perfectly same result as above 
tile

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]



array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 12. Create a 5x5 matrix with row values ranging from 0 to 4 using broadcasting


In [ ]:
a = np.arange(0,5)
tmp = np.zeros((5,1))
broadcasting_result = a + tmp
print(broadcasting_result)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 13. Create a random vector of size 10 and sort it 

In [ ]:
vector = np.random.random(10)
print(vector)
print()
sorted_vector = np.sort(vector)
print(sorted_vector)

[0.42812176 0.73417814 0.05754633 0.46001347 0.48546121 0.26352423
 0.50982484 0.63672837 0.39433018 0.71232306]

[0.05754633 0.26352423 0.39433018 0.42812176 0.46001347 0.48546121
 0.50982484 0.63672837 0.71232306 0.73417814]


#### 14. Subtract the mean of each row

X = np.random.rand(5,10)

In [ ]:
x = np.random.rand(5,10)
mean_arr = x.mean(axis = 1).reshape(5,1)
result = x - mean_arr
print(result)

[[-0.37253701 -0.13155494 -0.39835446  0.23473636  0.50681551  0.15556345
  -0.41210638  0.47655156 -0.20377911  0.14466501]
 [ 0.11352053 -0.20919647 -0.12484597  0.23382269  0.43657952  0.14350773
  -0.05156308 -0.12709437 -0.23950881 -0.17522177]
 [ 0.24799827 -0.17083493  0.25394695  0.18185756 -0.0730852  -0.29667506
   0.35484998 -0.21747161 -0.25106243 -0.02952352]
 [-0.44752551 -0.0084746  -0.10676363 -0.14307383  0.26036536  0.16873221
   0.43752587  0.38046823 -0.33328808 -0.20796602]
 [-0.05719858  0.46552237 -0.02498623  0.55430121 -0.22715057 -0.16571502
  -0.26460388 -0.32953027  0.22626183 -0.17690087]]


#### 15. Create, 10 by 10 multiplication table from 1 to 10

In [ ]:
a = np.arange(1,11)
b = a.reshape(10,1)
multiplication_table = a * b
print(multiplication_table) 

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


#### 16. How to get the diagonal of a dot product? 

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1, (5,5))

dot = A.dot(B)

print(np.diagonal(dot))

[1.02126711 0.40052411 1.03773738 1.32306615 0.82727472]


#### 17. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [ ]:
vector = np.array([1,2,3,4,5])
l = len(vector)
result = np.zeros(l + (l - 1)*3)
result[::4] = vector 
print(result)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 18. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

In [ ]:
# Professor's message

'''
Dear all,



Please ignore Question 18 in Homework #1.

The question is too difficult and complicated, and we did not cover the related issues in the class.

You can use numpy functions, any, all, newaixs.

Of course, you can answer the question.. but don't be too stressed out with the question.



Sincerely,

Sungshin Kim
'''

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)

print(A)
print()
print(B)
print()
rows = np.where(C.any((3,1)).all(1))[0]
print('indices of the rows which satisfy given conditions:', rows)

[[1 2 1]
 [3 4 4]
 [2 0 0]
 [0 1 4]
 [2 1 0]
 [0 0 2]
 [4 4 1]
 [4 4 2]]

[[3 2]
 [4 3]]

indices of the rows which satisfy given conditions: [1 7]


#### 19. How to swap two rows of an array? Generate an array from 0 to 24, and reshape it 5 by 5 and swap first two rows of the array

In [ ]:
arr = np.arange(0,25).reshape(5,5)
arr[0:2] = arr[1::-1] 
print(arr)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 20. How to find the most frequent value in an array? 

Z = np.random.randint(0,10,50). hint: np.bincount, np.argmax

In [ ]:
# This may be the Best answer that professor might be expecting.... 

Z = np.random.randint(0,10,50)
print(Z)
print()
freq = np.bincount(Z)
print(freq)
print()
most_freq_value = np.argmax(freq)
print('The most frequent value in the given array:', most_freq_value)

[6 1 3 6 0 4 6 2 8 4 1 1 4 4 6 2 4 1 8 5 2 4 4 0 9 3 0 5 3 3 3 4 3 7 2 3 4
 3 3 8 8 4 0 1 6 9 3 9 6 3]

[ 4  5  4 11 10  2  6  1  4  3]

The most frequent value in the given array: 3


In [ ]:
# However, Knowing that above code doesn't return actual value when they have more than 1 most frequent value, (e.g. [1,2,2,2,3,3,3] has 2 and 3 as its most frequent values)) 
# I came up with the below answers (one using argmax, another using argsort instead of argmax, the other not using both argmax and argsort)

In [ ]:
# Method which use argmax

Z = np.array([1,1,1,1,2,2,2,2,3,3,3,4,4,4,4])
print(Z)
print()
freq = np.bincount(Z)
print(freq)
print()
before = np.argmax(freq)
ans = [before]
l = freq[before]

while (True):
  tmp = list(Z)
  idx = tmp.index(before)
  reduced = np.delete(Z, idx)
  freq_tmp = np.bincount(reduced)
  after = np.argmax(freq_tmp)

  if ((after not in ans) and (freq_tmp[after] == l)):
    ans.append(after)
    before = after
    Z = reduced

  else:
    break


print('The most frequent values in the given array:', ans)

[1 1 1 1 2 2 2 2 3 3 3 4 4 4 4]

[0 4 4 3 4]

The most frequent values in the given array: [1, 2, 4]


In [ ]:
# Method which use argsort instead of argmax

from collections import Counter

Z = np.array([1,2,2,2,2,2,3,3,3,3,4])
print(Z)
print()
freq = np.bincount(Z)
print(freq)
print()
# most_freq_value = np.argmax(freq)
max_freq = np.max(freq)
n = len([idx for idx, val in enumerate(freq) if val == max_freq])

ans = np.argsort(freq)[::-1][n-1::-1]

print('The most frequent values in the given array:', ans)

[1 2 2 2 2 2 3 3 3 3 4]

[0 1 5 4 1]

The most frequent values in the given array: [2]


In [ ]:
# Method which doesn't use both argmax and argsort

from collections import Counter

Z = np.array([1,2,2,2,3,3,3,4])
print(Z)
print()
freq = np.bincount(Z)
print(freq)
print()
# most_freq_value = np.argmax(freq)
freq_how_many = np.max(freq)

count = Counter(Z)

val = np.array(list(count.values()))
key = np.array(list(count.keys()))
chk = (val == freq_how_many)

ans = key[chk]

print('The most frequent values in the given array:', ans)

[1 2 2 2 3 3 3 4]

[0 1 3 3 1]

The most frequent values in the given array: [2 3]


#### 21. How to get the n largest values of an array?

start with 
Z = np.arange(10000);
np.random.shuffle(Z)
, Hint: np.argsort

In [ ]:
Z = np.arange(10000)
print("Shuffled array")
np.random.shuffle(Z)
print(Z)
print()

n = int(input('n = '))
arg_sort = np.argsort(Z)
where = arg_sort[-n:]
print("Find indices of the n largest values")
print(where)
print()
print("Find the n largest values of shuffled array")
find = Z[where]
print(find)

Shuffled array
[6747 5042 9659 ... 9520 2465 1548]

n = 10
Find indices of the n largest values
[3423 1001 5847 2439 8966 9802 1695 6148 5442 7024]

Find the n largest values of shuffled array
[9990 9991 9992 9993 9994 9995 9996 9997 9998 9999]


#### 22. Given a two dimensional array, how to extract unique rows? 

Hint: np.unique

In [ ]:
row = int(input('row size:'))
column = int(input('column size:'))
Z = np.random.randint(2, size = row*column).reshape(row, column)
print()

print(Z)
print()
unique_rows = np.unique(Z, axis=0)
print(unique_rows)

row size:5
column size:3

[[0 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 0]
 [1 1 1]]

[[0 0 0]
 [0 0 1]
 [1 1 1]]


#### 23. How to compute averages using a sliding window over an array? 

make a function with two arguments, array and size of the sliding window, def moving_avg(arr, n)


In [9]:
def moving_avg(arr, n):
  moving_avg = []
  for i in range(len(arr)-(n-1)):
    tmp = np.mean(arr[i:i+n])
    moving_avg.append(tmp)
  
  return moving_avg

arr = np.arange(10)
k = int(input('window size:'))
print()
print(np.tile(arr, (len(arr)-k+1,1)))
print()
ans = moving_avg(arr, k)
print("averages of sliding windows:", ans)

window size:4

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]

averages of sliding windows: [1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5]


In [6]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(10)
print(moving_average(Z, n=3))

[1. 2. 3. 4. 5. 6. 7. 8.]


#### 24. Find the indices of elements from 4 by 4 random matrix (0-1) which are larger than 0.5

Print a list of tuples indicating the index for row and column


In [ ]:
a = np.random.random((4,4))
print(a)
print()
id = np.nonzero(a>0.5)
coordinates = [*zip(id[0],id[1])]
print(coordinates)

[[0.48835607 0.20884305 0.07656698 0.7572095 ]
 [0.9005907  0.48258304 0.29794201 0.18510508]
 [0.07834579 0.17902419 0.86796678 0.8081418 ]
 [0.30917439 0.60443227 0.43998796 0.15286133]]

[(0, 3), (1, 0), (2, 2), (2, 3), (3, 1)]


#### 25. Write a function returning distance between two points

Test the function to check whether function is working correctly
Hint: There are two arguments of function indicating two points

In [ ]:
def distance(p1,p2):
  x_d = p1[0] - p2[0]
  y_d = p1[1] - p2[1]
  distance = np.sqrt((x_d)**2 + (y_d)**2)
  return distance

print('Enter x, y value of p1')
x1 = float(input('x:'))
y1 = float(input('y:'))
print()
print('Enter x, y value of p2')
x2 = float(input('x:'))
y2 = float(input('y:'))

p1 = (x1, y1)
p2 = (x2, y2)

print()
d = distance(p1, p2)
print("Distance:", d)

Enter x, y value of p1
x:5
y:2

Enter x, y value of p2
x:3
y:3

Distance: 2.23606797749979
